name: Build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ocaml-version:
          - 4.12.x

    steps:
      - name: Install external dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gcc wget cmake

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install OCaml dependencies
        run: |
          opam update
          opam install -y graphics num
          eval $(opam env)
          echo XXXXXXXXXXX $PATH
          which ocamlc
          ocamlc -v

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ReactiveML
        run: |
          echo XXXXXXXXXXX $PATH
          eval $(opam env)
          echo XXXXXXXXXXX $PATH
          which ocamlc
          ocamlc -v
          ./configure
          make
          make install

      - name: Build all examples
        run: |
          cd examples
          make
