name: Build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler:
          - 4.12.0

    steps:
      - name: Install external dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gcc wget cmake

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Setup opam switch
        run: |
          opam switch create ${{ matrix.ocaml-compiler }}
          opam update
          opam install -y ocamlfind graphics num
          echo "OPAM_SWITCH_PREFIX=$HOME/.opam/${{ matrix.ocaml-compiler }}" >> $GITHUB_ENV
          echo "CAML_LD_LIBRARY_PATH=$HOME/.opam/${{ matrix.ocaml-compiler }}/lib/stublibs:$HOME/.opam/${{ matrix.ocaml-compiler }}/lib/ocaml/stublibs:$HOME/.opam/${{ matrix.ocaml-compiler }}/lib/ocam" >> $GITHUB_ENV
          echo "$HOME/.opam/${{ matrix.ocaml-compiler }}/bin" >> $GITHUB_PATH
          echo "/home/opam/.opam/${{ matrix.ocaml-compiler }}/bin" >> $GITHUB_PATH
          echo XXXX $HOME
          echo XXX OPAM:
          opam env
	  echo XXXXXXXX
          echo "OPAM_SWITCH_PREFIX=$HOME/.opam/${{ matrix.ocaml-compiler }}"
          echo "CAML_LD_LIBRARY_PATH=$HOME/.opam/${{ matrix.ocaml-compiler }}/lib/stublibs:$HOME/.opam/${{ matrix.ocaml-compiler }}/lib/ocaml/stublibs:$HOME/.opam/${{ matrix.ocaml-compiler }}/lib/ocam"
          echo "$HOME/.opam/${{ matrix.ocaml-compiler }}/bin"
          echo "/home/opam/.opam/${{ matrix.ocaml-compiler }}/bin"
	  echo XXXXXXXX
          ocamlfind

      - name: Install ReactiveML
        run: |
          ./configure --prefix $HOME/.local
          make
          make install
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build all examples
        run: |
          ls $HOME/.local/bin
          $HOME/.local/bin/rmlc -v
          cd examples
          make
