name: Build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler:
          - 4.12.0

    steps:
      - name: Install external dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gcc wget cmake

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install ReactiveML
        run: |
          opam update
          opam install -y graphics num
          eval $(opam env)
          ./configure --prefix $HOME/local
          make
          make install
          export PATH=$HOME/local/bin:$PATH

      - name: Build all examples
        run: |
          cd examples
          make
